# -*- coding: utf-8 -*-
"""matplotlibbasic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s4OPg3BmTMvoFMPlG8vo9e-_GYYQMFzR

Matplotlib-useful for making plots
"""

#importing matplot lib library
import matplotlib.pyplot as plt

#import numpy to get data for plots
import numpy as np

x=np.linspace(0,10,100)
y=np.sin(x)
z=np.cos(x)

print(x)

print(y)

print(z)

"""# **Plotting the data**"""

#sin wave
plt.plot(x,y)
plt.show()

#cos wave
plt.plot(x,z)
plt.show()

#adding title to x and y axis lables
plt.plot(x,y)
plt.xlabel("angle")
plt.ylabel("sine value")
plt.title("sine wave")
plt.show()

#parabola
x=np.linspace(-10,10,20)
y=x**2
plt.plot(x,y)
plt.show()

plt.plot(x,y,'r.')
plt.show()

x=np.linspace(-5,5,50)
plt.plot(x,np.sin(x),'r.')
plt.plot(x,np.cos(x),"b--")
plt.show()

"""# **Bar plot**"""

fig=plt.figure()
ax=fig.add_axes([0,0,1,1])
languages=["english","Tamil","kannada"]
people=[100,200,50]
ax.bar(languages,people)
plt.xlabel("Languages")
plt.ylabel("Peoples")
plt.show()

"""# **pie chart**"""

fig1=plt.figure()
ax=fig1.add_axes([0,0,1,1])
languages=["english","Tamil","kannada"]
people=[100,200,50]
ax.pie(people,labels=languages,autopct="1%.1f%%")
plt.show()

"""# **scatter plot**"""

x=np.linspace(0,10,30)
y=np.sin(x)
z=np.cos(x)
fig2=plt.figure()
ax=fig2.add_axes([0,0,1,1])
ax.scatter(x,y,color="g")
ax.scatter(x,z,color="r")
plt.show()

"""# **3D scatter-plot**"""

fig3=plt.figure()
ax=plt.axes(projection="3d")
z=20* np.random.random(100)
x=np.sin(z)
y=np.cos(z)
ax.scatter(x,y,z,c=z,cmap="Greens")
plt.show()

